import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'
import fetchGraphQL from '../lib/fetchGithubGraphQL';

const Home: NextPage = () => {

const [repoName, setRepoName] = useState<string>('');
const [accountName, setAccountName] = useState<string>('');

  useEffect(() => { 
    let isMounted = true;
    fetchGraphQL(`
      query RepositoryNameQuery {
        repository(owner: "Yosuke23", name: "newrepo") {
          name
        },
        user(login: "Yosuke23") {
          name
        }
      }
    `, {}).then(response => {
      if (!isMounted) {
        return;
      }
      const data = response.data;
      console.log(response);
      setRepoName(data.repository.name);
      setAccountName(data.user.name);
    }).catch(error => {
      console.error(error);
    });


    return () => {
      isMounted = false;
    };
  }, [fetchGraphQL]);
  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Demo App with NextApp & Relay</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={`${styles.title}`}>
          Create Demo App with <a href="https://nextjs.org">NextApp</a>& Relay
        </h1> */}

        <p className="text-gray-200 mt-96">
          {accountName !== '' ? `UserName(logged in User): ${accountName}` : 'Loading...'} 
        </p>
        <p>
          {accountName !== '' ? `Repository: ${repoName}` : 'Loading...'} 
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
